# Generated by Django 3.0.5 on 2020-06-27 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=10)),
                ('division', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Noida', 'Noida')], max_length=20)),
                ('experience', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('date_posted', models.DateField()),
                ('date_expiry', models.DateField()),
                ('location', models.CharField(choices=[('Bangalore', 'Bangalore'), ('Noida', 'Noida')], max_length=20)),
                ('skills', models.TextField()),
                ('job_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=15)),
                ('current_level', models.IntegerField()),
                ('current_designation', models.CharField(max_length=50)),
                ('current_division', models.CharField(choices=[('SP & T', 'SP & T'), ('Managed Services', 'Managed Services')], max_length=20)),
                ('skills', models.TextField()),
                ('reporting_manager', models.CharField(max_length=100)),
                ('reporting_lead', models.CharField(max_length=100)),
                ('current_project', models.CharField(max_length=200)),
                ('duration_in_current_Level', models.FloatField(max_length=20)),
                ('last_promotion_if_any_and_when', models.CharField(max_length=300)),
                ('date_applied', models.DateField()),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internal_jobs.JobRequirement')),
            ],
        ),
    ]
