# Generated by Django 3.0.5 on 2020-06-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_jobs', '0002_auto_20200628_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Joined', 'Joined')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='skills',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jobrequirement',
            name='skills',
            field=models.CharField(max_length=500),
        ),
    ]
