# Generated by Django 3.0.5 on 2020-06-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cu_id', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('designation', models.CharField(max_length=100)),
                ('employee_type', models.CharField(choices=[('Permanent', 'Permanent'), ('Contract', 'Contract')], max_length=20)),
                ('emp_level', models.IntegerField()),
                ('employee_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=10)),
                ('contact', models.CharField(max_length=12)),
                ('joining_date', models.DateField()),
                ('skill_set', models.TextField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Other', 'Other')], max_length=10)),
                ('emp', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
